server:
  port: 8080
  error:
    include-stacktrace: NEVER

logging:
  level:
    org.springframework.security: DEBUG
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/user_service?userTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: example
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update